### ISSUE TITLE
SimpleSearch not working

### ISSUE THREAD

**Issue by JvdW** [AssetTracker/rt-extension-assettracker#12] opened 2011-10-31 14:22 UTC
Hello Todd,

I discovered that the quicksearch at the top of the screen doesn't search Assets when you're at the asset screen but it searches for tickets instead.
To fix this is a one line modification to Callbacks/Elements/Tabs/Privileged namely insert the following:
PageWidgets()->child( simple_search => raw_html => $m->scomp('SimpleSearch'), sort_order => 98 );
after the PageWidgets() -> child( create_asset ....) line

Greetings,

Joop

**Comment by JvdW** [comment] 2011-11-11 10:42
The solution above is a bit rough, the following takes into consideration where in RT you are. It will display the Asset Simple search when AssetTracker is part of the URL and you'll get the RT Simple search otherwise.

if ( $request_path =~ m{^/AssetTracker/} ) {
        PageWidgets()->child( simple_search => raw_html => $m->scomp('/AssetTracker/Elements/SimpleSearch'), sort_order => 98 );
}

**Comment by dentm42** [comment] 2011-11-17 03:43
Actually, the problem is the widget ends up overwriting the ticket search widget.  The fix is to change the line to read:

PageWidgets()->child( AT_simple_search => raw_html => $m->scomp('/AssetTracker/Elements/SimpleSearch'), sort_order => 98 );

You may still want to wrap it in the IF statement and maybe the "create_asset" widget too, if you don't add/search assets often.  I kind of like it that way since I don't create/quicksearch assets often.

Finally, it might be wise to change /AssetTracker/Elements/SimpleSearch to say "Search Assets..." instead of just "Search" to help users know why there are 2 different boxes.

**Comment by btb** [comment] 2013-04-06 23:13
fixed in 763e500c9616f5efe7fcf4fbcfe5d822196ec4ce

**Closed as completed by btb** 2013-04-06 23:13 UTC
