### ISSUE TITLE
Asset link is "0" in Ticket link columns

### ISSUE THREAD

**Issue by jcharaoui** [AssetTracker/rt-extension-assettracker#42] opened 2012-11-23 18:03 UTC
When displaying relationship columns in Ticket search results, Assets which are linked are shown as "0", though the hyperlink works.

**Comment by btb** [comment] 2012-11-23 19:55
This may be more of an issue with RT, you'll notice that article links behave the same way. The problem is that the asset (and article) uri objects report themselves as "local" and the Ticket ColumnMap takes that to mean it lives in the Tickets table.

**Comment by btb** [comment] 2013-06-19 02:29
fixed in stable branch of rt

**Closed as completed by btb** 2013-06-19 02:29 UTC
